#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TypeSafe 文档中文化审计器（零第三方依赖，仅标准库）。

功能
----
1. 逐文件统计 CJK 占比与词数，分类为 未翻译 / 部分翻译 / 已翻译（阈值可配）；
   自动生成内容（sdk/** 等）单独归类为 generated，不计入人工翻译范围。
2. 混排检测：在中文文件里找出残留的英文段落，输出 文件 + 行号 + 原文。
3. 结构保真：围栏代码块（含逐字节内容指纹）、行内代码、链接目标、图片、
   Mermaid 块、MDX/JSX 组件、标题层级、锚点、表格。
   - 给了 --source-dir（英文原文目录）时逐项比对；
   - 没有英文原文时，退化为启发式检查 + 与 --baseline 快照比对回归。
4. 导航覆盖：docs.json 引用的每个页面必须在磁盘上存在（死链），
   并报告哪些导航条目（tab / group 标签、页面）仍未翻译。
5. 术语表合规：按 tools/glossary.yml 的推荐译法 / 禁用译法检查。

输出
----
人类可读摘要默认打到 stdout；--json PATH 写完整 JSON 报告（供 CI 消费）。
--strict 时任何 error 级问题都会让退出码变成 1。

示例
----
    python tools/i18n_audit.py
    python tools/i18n_audit.py --strict --json i18n-report.json
    python tools/i18n_audit.py --write-baseline tools/structure-baseline.json
    python tools/i18n_audit.py --source-dir ../typesafe-docs
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from hashlib import sha1
from pathlib import Path

# --------------------------------------------------------------------------
# 正则与常量
# --------------------------------------------------------------------------

TICK = "\x60"
FENCE_RE = re.compile(r"^(\s*)(\x60{3,}|~{3,})(.*)$")
CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
LATIN_WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]*")
INLINE_CODE_RE = re.compile(r"(\x60+)([^\x60]+?)\1")
IMAGE_RE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
IMG_TAG_RE = re.compile(r"<img\b[^>]*\bsrc=\"([^\"]+)\"", re.I)
LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
HREF_RE = re.compile(r"\bhref=[\"']([^\"']+)[\"']")
AUTOLINK_RE = re.compile(r"<https?://[^>]+>")
HTML_TAG_RE = re.compile(r"</?[A-Za-z][A-Za-z0-9-]*(?:\s[^<>]*)?/?>")
URL_RE = re.compile(r"https?://\S+")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$")
COMPONENT_RE = re.compile(r"<([A-Z][A-Za-z0-9]*)[\s/>]")
ANCHOR_RE = re.compile(r"\{#([A-Za-z0-9_.:-]+)\}")
JS_FUNC_RE = re.compile(r"^(export\s+)?(async\s+)?function\s+[A-Za-z_$]")
JS_EXPORT_RE = re.compile(r"^export\s+(default\s+)?(const|let|var|class)\s")
JSX_OPEN_RE = re.compile(r"^</?[A-Za-z][A-Za-z0-9.-]*")
ATTR_TEXT_RE = re.compile(r'\b(title|description|label|summary|placeholder)\s*=\s*"([^"]*)"')
GENERATED_MARKERS = (
    "auto-generated",
    "automatically generated",
    "此文件由",
    "由工具自动生成",
    "do not edit",
    "generated by",
)

DEFAULT_EXCLUDES = (".git", "node_modules", ".mintlify", "tools", ".github", ".vercel", "dist", "build")
GENERATED_PREFIXES = ("sdk/",)
# 仓库自身的说明文档，不是站点页面：不参与覆盖率统计，混排问题降级为 warning。
META_FILES = ("README.md", "TRANSLATING.md", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md")


def word_count(text):
    """中文按字计，拉丁文按词计。"""
    return len(CJK_RE.findall(text)) + len(LATIN_WORD_RE.findall(text))


def score_text(text):
    """返回 (cjk_char_count, latin_word_count, latin_letter_count)。"""
    cjk = len(CJK_RE.findall(text))
    words = LATIN_WORD_RE.findall(text)
    latin_letters = sum(len(w) for w in words)
    return cjk, len(words), latin_letters


def cjk_ratio(cjk, latin_letters):
    denom = cjk + latin_letters
    if denom == 0:
        return 0.0
    return cjk / denom


# --------------------------------------------------------------------------
# Markdown 分行分类
# --------------------------------------------------------------------------
# kind 取值：
#   frontmatter  文件头 YAML
#   fence        围栏代码块内部
#   fence_marker 围栏标记行本身
#   js           export function / 顶层 JS 区域
#   jsx_tag      JSX 组件标签行
#   jsx_attr     组件属性跨行区域
#   prose        正文（唯一参与中文化统计的行）


def classify_lines(lines):
    out = []
    in_front = False
    front_seen = False
    fence = None
    js_region = False
    tag_region = False

    for idx, raw in enumerate(lines):
        n = idx + 1
        s = raw.strip()

        if in_front:
            if s == "---":
                in_front = False
            out.append((n, raw, "frontmatter"))
            continue
        if idx == 0 and s == "---":
            in_front = True
            front_seen = True
            out.append((n, raw, "frontmatter"))
            continue

        if fence is not None:
            m = FENCE_RE.match(raw)
            if m and m.group(2)[0] == fence[0] and len(m.group(2)) >= fence[1] and m.group(3).strip() == "":
                fence = None
                out.append((n, raw, "fence_marker"))
            else:
                out.append((n, raw, "fence"))
            continue

        m = FENCE_RE.match(raw)
        if m and s:
            fence = (m.group(2)[0], len(m.group(2)))
            out.append((n, raw, "fence_marker"))
            continue

        if js_region:
            if raw and not raw[0].isspace() and s == "}":
                js_region = False
            out.append((n, raw, "js"))
            continue

        if JS_FUNC_RE.match(raw) or JS_EXPORT_RE.match(raw):
            js_region = not (s.endswith("}") and not s.endswith("{"))
            out.append((n, raw, "js"))
            continue

        if tag_region:
            if s.endswith("/>") or (s.endswith(">") and not s.endswith("=>")):
                tag_region = False
            out.append((n, raw, "jsx_attr"))
            continue

        if s.startswith("<") and JSX_OPEN_RE.match(s):
            closes = s.endswith("/>") or (s.endswith(">") and not s.endswith("=>"))
            tag_region = not closes
            out.append((n, raw, "jsx_tag"))
            continue

        out.append((n, raw, "prose"))

    return out


def scrub(line):
    """去掉 markdown / 链接 / 行内代码 / HTML 标记，只留下散文。"""
    t = line.strip()
    t = IMAGE_RE.sub(" ", t)
    t = LINK_RE.sub(lambda m: m.group(1), t)
    t = INLINE_CODE_RE.sub(" ", t)
    t = AUTOLINK_RE.sub(" ", t)
    t = HTML_TAG_RE.sub(" ", t)
    t = URL_RE.sub(" ", t)
    t = HREF_RE.sub(" ", t)
    t = re.sub(r"^#{1,6}\s*", "", t)
    t = re.sub(r"^>\s*", "", t)
    t = re.sub(r"^[-*+]\s+", "", t)
    t = re.sub(r"^\d+[.)]\s+", "", t)
    t = t.replace("|", " ")
    t = re.sub(r"[*_~]+", " ", t)
    t = re.sub(r"\s+", " ", t)
    return t.strip()


# --------------------------------------------------------------------------
# 结构指纹
# --------------------------------------------------------------------------


def strip_trailing_comment(line):
    """去掉行尾注释（# 或 //），只保留代码本身。字符串里的 # 处理方式两侧一致，不影响比对。"""
    for marker in ("#", "//"):
        cut = None
        for i in range(1, len(line)):
            if line.startswith(marker, i) and line[i - 1].isspace() and line[:i].strip():
                cut = i
                break
        if cut is not None:
            line = line[:cut].rstrip()
    return line


def code_only_lines(body):
    """丢掉注释后的代码正文，用于区分 代码被改 与 代码注释被翻译。"""
    kept = []
    for ln in body:
        s = ln.strip()
        if s.startswith("#") or s.startswith("//") or s.startswith("--") or s.startswith("<!--"):
            continue
        kept.append(strip_trailing_comment(ln))
    return kept


def mermaid_skeleton(body):
    """Mermaid 的节点 ID 与连线不能动，节点里的可读标签可以翻译：比对时先把引号里的标签抹掉。"""
    text = "\n".join(body)
    text = re.sub(r'"[^"]*"', '""', text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def h(text):
    return sha1(text.encode("utf-8")).hexdigest()[:16]


def structure_of(lines, regions):
    kinds = {n: k for n, _, k in regions}
    body_lines = [ln for n, ln, k in regions if k not in ("fence", "fence_marker")]
    whole = "\n".join(body_lines)
    fence_text = "\n".join(ln for n, ln, k in regions if k != "fence")

    fences = []
    cur = None
    for n, ln, k in regions:
        if k == "fence_marker":
            m = FENCE_RE.match(ln)
            if cur is None and m and ln.strip():
                cur = {"line": n, "lang": m.group(3).strip().split()[0] if m.group(3).strip() else "", "body": []}
            elif cur is not None:
                cur["raw_sha"] = h("\n".join(cur["body"]))
                if cur["lang"].startswith("mermaid"):
                    cur["code_sha"] = h(mermaid_skeleton(cur["body"]))
                else:
                    cur["code_sha"] = h("\n".join(code_only_lines(cur["body"])))
                fences.append(cur)
                cur = None
        elif k == "fence" and cur is not None:
            cur["body"].append(ln)

    inline = Counter(INLINE_CODE_RE.findall(whole))
    inline.pop("", None)
    inline_code = Counter()
    for m in INLINE_CODE_RE.finditer(whole):
        inline_code[m.group(2).strip()] += 1

    links = set()
    for m in LINK_RE.finditer(fence_text):
        links.add(m.group(2))
    for m in HREF_RE.finditer(fence_text):
        links.add(m.group(1))
    images = set(m.group(1) for m in IMAGE_RE.finditer(fence_text))
    images |= set(m.group(1) for m in IMG_TAG_RE.finditer(fence_text))

    headings = []
    for n, ln, k in regions:
        if k != "prose":
            continue
        m = HEADING_RE.match(ln.strip())
        if m:
            headings.append({"line": n, "level": len(m.group(1)), "text": scrub(ln)})

    anchors = set(ANCHOR_RE.findall(fence_text))
    components = sorted(set(COMPONENT_RE.findall(fence_text)))
    tables = sum(1 for n, ln, k in regions if k == "prose" and TABLE_SEP_RE.match(ln))

    mermaid = [f for f in fences if f["lang"].startswith("mermaid")]

    return {
        "fence_count": len(fences),
        "fence_langs": [f["lang"] for f in fences],
        "fence_code_sha": [f.get("code_sha", "") for f in fences],
        "fence_raw_sha": [f.get("raw_sha", "") for f in fences],
        "mermaid_count": len(mermaid),
        "mermaid_sha": [f.get("code_sha", "") for f in mermaid],
        "inline_code": dict(sorted(inline_code.items())),
        "links": sorted(links),
        "images": sorted(images),
        "components": components,
        "headings": [{"level": x["level"], "text": x["text"]} for x in headings],
        "heading_count": len(headings),
        "anchors": sorted(anchors),
        "table_count": tables,
    }


# --------------------------------------------------------------------------
# 混排检测
# --------------------------------------------------------------------------


def find_mixed(regions, allow, heading_min_words, prose_min_words):
    findings = []
    block = []

    def flush():
        if not block:
            return
        findings.append(
            {
                "start_line": block[0]["line"],
                "end_line": block[-1]["line"],
                "kind": block[0]["kind"],
                "words": sum(b["words"] for b in block),
                "text": " / ".join(b["text"] for b in block)[:400],
            }
        )
        block.clear()

    for n, raw, kind in regions:
        if kind == "jsx_tag":
            for am in ATTR_TEXT_RE.finditer(raw):
                text = scrub(am.group(2))
                if not text:
                    continue
                cjk, words, letters = score_text(text)
                if cjk == 0 and words >= prose_min_words and letters >= prose_min_words * 3:
                    block.append({"line": n, "words": words, "text": text[:200], "kind": "jsx_attr"})
            continue
        if kind != "prose":
            flush()
            continue
        s = raw.strip()
        if not s:
            flush()
            continue
        text = scrub(s)
        if not text:
            flush()
            continue
        if any(rx.search(s) or rx.search(text) for rx in allow):
            flush()
            continue
        cjk, words, letters = score_text(text)
        if cjk > 0:
            flush()
            continue
        is_heading = bool(HEADING_RE.match(s))
        limit = heading_min_words if is_heading else prose_min_words
        if words >= limit and letters >= limit * 3:
            block.append({"line": n, "words": words, "text": text[:200], "kind": "heading" if is_heading else "prose"})
        else:
            flush()
    flush()
    return findings


# --------------------------------------------------------------------------
# 术语表（YAML 子集解析，优先 PyYAML，缺失时用自带解析器）
# --------------------------------------------------------------------------


class MiniYaml:
    """极简 YAML 解析器：支持缩进块映射 / 序列、行内 [a, b]、引号标量、# 注释。"""

    def __init__(self, text):
        self.tokens = self._tokenize(text)
        self.i = 0

    @staticmethod
    def _strip_comment(line):
        out = []
        quote = None
        for ch in line:
            if quote:
                out.append(ch)
                if ch == quote:
                    quote = None
                continue
            if ch in "\"'":
                quote = ch
                out.append(ch)
                continue
            if ch == "#" and (not out or out[-1] in " \t"):
                break
            out.append(ch)
        return "".join(out)

    def _tokenize(self, text):
        toks = []
        for raw in text.replace("\t", "    ").splitlines():
            line = self._strip_comment(raw).rstrip()
            if not line.strip():
                continue
            indent = len(line) - len(line.lstrip(" "))
            toks.append([indent, line.strip()])
        return toks

    @staticmethod
    def _scalar(v):
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            return v[1:-1]
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            if not inner:
                return []
            parts, buf, quote = [], [], None
            for ch in inner:
                if quote:
                    buf.append(ch)
                    if ch == quote:
                        quote = None
                    continue
                if ch in "\"'":
                    quote = ch
                    buf.append(ch)
                    continue
                if ch == ",":
                    parts.append("".join(buf))
                    buf = []
                    continue
                buf.append(ch)
            parts.append("".join(buf))
            return [MiniYaml._scalar(p) for p in parts if p.strip()]
        if v in ("null", "~"):
            return None
        if v == "true":
            return True
        if v == "false":
            return False
        return v

    def parse(self):
        if not self.tokens:
            return None
        return self._node(self.tokens[0][0])

    def _node(self, indent):
        if self.i >= len(self.tokens):
            return None
        if self.tokens[self.i][1].startswith("- "):
            return self._seq(indent)
        return self._map(indent)

    def _seq(self, indent):
        items = []
        while self.i < len(self.tokens):
            ind, content = self.tokens[self.i]
            if ind != indent or not content.startswith("- "):
                break
            rest = content[2:].strip()
            if not rest:
                self.i += 1
                items.append(self._node(self.tokens[self.i][0]) if self.i < len(self.tokens) and self.tokens[self.i][0] > indent else None)
                continue
            self.tokens[self.i] = [indent + 2, rest]
            items.append(self._node(indent + 2))
        return items

    def _map(self, indent):
        out = {}
        while self.i < len(self.tokens):
            ind, content = self.tokens[self.i]
            if ind != indent or content.startswith("- "):
                break
            if ":" not in content:
                self.i += 1
                continue
            key, _, val = content.partition(":")
            key = key.strip()
            val = val.strip()
            if val:
                out[key] = self._scalar(val)
                self.i += 1
            else:
                self.i += 1
                if self.i < len(self.tokens) and self.tokens[self.i][0] > indent:
                    out[key] = self._node(self.tokens[self.i][0])
                else:
                    out[key] = None
        return out


def load_glossary(path):
    if not path.exists():
        return None, "missing"
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore

        return yaml.safe_load(text), "pyyaml"
    except Exception:
        pass
    try:
        return MiniYaml(text).parse(), "builtin"
    except Exception as exc:  # pragma: no cover
        return None, "error: %s" % exc


# --------------------------------------------------------------------------
# 导航
# --------------------------------------------------------------------------


def collect_nav_pages(node, out):
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "pages" and isinstance(v, list):
                for item in v:
                    if isinstance(item, str):
                        out.append(item)
                    else:
                        collect_nav_pages(item, out)
            elif isinstance(v, (dict, list)):
                collect_nav_pages(v, out)
    elif isinstance(node, list):
        for item in node:
            collect_nav_pages(item, out)


def collect_nav_labels(node, out):
    if isinstance(node, dict):
        for k, v in node.items():
            if k in ("tab", "group") and isinstance(v, str):
                out.append(v)
            elif isinstance(v, (dict, list)):
                collect_nav_labels(v, out)
    elif isinstance(node, list):
        for item in node:
            collect_nav_labels(item, out)


def resolve_page(root, page):
    for cand in (page + ".md", page + ".mdx", page + "/index.md", page + "/index.mdx"):
        if (root / cand).exists():
            return cand
    return None


# --------------------------------------------------------------------------
# 主审计
# --------------------------------------------------------------------------


def audit(args):
    root = Path(args.root).resolve()
    allow = []
    glossary, glossary_src = load_glossary(root / args.glossary)
    if glossary:
        for item in glossary.get("allow") or []:
            if isinstance(item, dict) and item.get("pattern"):
                try:
                    allow.append(re.compile(item["pattern"]))
                except re.error:
                    pass

    files = []
    for pattern in ("*.md", "*.mdx"):
        for p in sorted(root.rglob(pattern)):
            rel = p.relative_to(root).as_posix()
            if any(part in DEFAULT_EXCLUDES for part in rel.split("/")):
                continue
            files.append((rel, p))
    files = sorted(set(files))

    report = {
        "schema": "typesafe-docs-zh/i18n-audit@1",
        "root": str(root),
        "thresholds": {
            "untranslated_below": args.untranslated_below,
            "translated_above": args.translated_above,
            "mixed_min_words": args.mixed_min_words,
            "heading_min_words": args.heading_min_words,
            "min_prose_words": args.min_prose_words,
        },
        "glossary_source": glossary_src,
        "files": {},
        "checks": {},
        "errors": [],
        "warnings": [],
    }

    for rel, path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        regions = classify_lines(lines)

        prose_units = []
        for n, raw, kind in regions:
            if kind == "frontmatter":
                m = re.match(r"^(title|description)\s*:\s*(.+)$", raw.strip())
                if m:
                    prose_units.append((n, m.group(2), "frontmatter"))
                continue
            if kind == "jsx_tag":
                for am in ATTR_TEXT_RE.finditer(raw):
                    val = scrub(am.group(2))
                    if val:
                        prose_units.append((n, val, "jsx_attr"))
                continue
            if kind != "prose":
                continue
            scrubbed = scrub(raw)
            if scrubbed:
                prose_units.append((n, scrubbed, "prose"))

        prose_text = " ".join(u[1] for u in prose_units)
        cjk, latin_words, latin_letters = score_text(prose_text)
        ratio = cjk_ratio(cjk, latin_letters)
        words = word_count(prose_text)

        raw_body = "\n".join(ln for _, ln, k in regions if k in ("prose", "fence"))
        rcjk, _, rletters = score_text(raw_body)
        raw_ratio = cjk_ratio(rcjk, rletters)

        head = "\n".join(lines[:40]).lower()
        generated = rel.startswith(GENERATED_PREFIXES) or any(m in head for m in GENERATED_MARKERS)

        if generated:
            category = "generated"
        elif rel in META_FILES:
            category = "meta"
        elif words < args.min_prose_words:
            category = "index"
        elif ratio >= args.translated_above:
            category = "translated"
        elif ratio < args.untranslated_below:
            category = "untranslated"
        else:
            category = "partial"

        entry = {
            "category": category,
            "lines": len(lines),
            "prose_words": words,
            "cjk_chars": cjk,
            "latin_words": latin_words,
            "cjk_ratio": round(ratio, 4),
            "raw_cjk_ratio": round(raw_ratio, 4),
            "structure": structure_of(lines, regions),
            "mixed": [],
            "notes": [],
        }
        if category in ("translated", "partial"):
            entry["mixed"] = find_mixed(regions, allow, args.heading_min_words, args.mixed_min_words)
        report["files"][rel] = entry

    # ---------------- 覆盖率 ----------------
    human = [k for k, v in report["files"].items() if v["category"] not in ("generated", "meta")]
    counts = Counter(report["files"][k]["category"] for k in report["files"])
    words_by_cat = Counter()
    for k in report["files"]:
        words_by_cat[report["files"][k]["category"]] += report["files"][k]["prose_words"]
    total_words = sum(words_by_cat.values())
    done_words = words_by_cat["translated"] + words_by_cat["partial"]
    report["checks"]["coverage"] = {
        "files_total": len(report["files"]),
        "files_in_scope": len(human),
        "files_by_category": dict(counts),
        "prose_words_total": total_words,
        "prose_words_by_category": dict(words_by_cat),
        "file_coverage": round(counts.get("translated", 0) / len(human), 4) if human else 0.0,
        "word_coverage": round(done_words / total_words, 4) if total_words else 0.0,
    }

    # ---------------- 混排 ----------------
    mixed = []
    for rel, entry in report["files"].items():
        for f in entry["mixed"]:
            mixed.append(dict(f, path=rel))
    mixed.sort(key=lambda x: (x["path"], x["start_line"]))
    report["checks"]["mixed_language"] = {
        "findings": mixed,
        "count": len(mixed),
        "files": sorted(set(m["path"] for m in mixed)),
    }
    for m in mixed:
        if report["files"][m["path"]]["category"] == "meta":
            report["warnings"].append(
                "混排：仓库文档 %s:%d 含英文行：%s" % (m["path"], m["start_line"], m["text"][:80])
            )
        elif report["files"][m["path"]]["category"] == "translated":
            report["errors"].append(
                "混排：已翻译文件 %s:%d 仍有整段英文：%s" % (m["path"], m["start_line"], m["text"][:80])
            )
        else:
            report["warnings"].append(
                "混排：部分翻译文件 %s:%d 仍有英文段落：%s" % (m["path"], m["start_line"], m["text"][:80])
            )

    # ---------------- 导航 ----------------
    docs_path = root / args.docs
    nav = {"exists": docs_path.exists(), "pages": 0, "missing": [], "untranslated": [], "generated": [], "labels_untranslated": []}
    if docs_path.exists():
        try:
            docs = json.loads(docs_path.read_text(encoding="utf-8"))
        except Exception as exc:
            report["errors"].append("docs.json 不是合法 JSON：%s" % exc)
            docs = None
        if docs is not None:
            pages = []
            collect_nav_pages(docs.get("navigation", {}), pages)
            nav["pages"] = len(pages)
            for page in pages:
                resolved = resolve_page(root, page)
                if not resolved:
                    nav["missing"].append(page)
                    report["errors"].append("导航死链：docs.json 引用了不存在的页面 %s" % page)
                    continue
                cat = report["files"].get(resolved, {}).get("category")
                if cat in ("untranslated", "partial"):
                    nav["untranslated"].append({"page": page, "file": resolved, "category": cat})
                elif cat == "generated":
                    nav["generated"].append(page)
            labels = []
            collect_nav_labels(docs.get("navigation", {}), labels)
            for label in dict.fromkeys(labels):
                if not CJK_RE.search(label) and not any(rx.search(label) for rx in allow):
                    nav["labels_untranslated"].append(label)
            if nav["labels_untranslated"]:
                report["warnings"].append("导航标签未翻译：%s" % ", ".join(nav["labels_untranslated"]))
    else:
        report["errors"].append("找不到 %s" % args.docs)
    report["checks"]["navigation"] = nav

    # ---------------- 术语表 ----------------
    terms = {"entries": 0, "violations": [], "missing_zh": [], "english_in_prose": []}
    if glossary is None:
        report["warnings"].append("未找到术语表 %s" % args.glossary)
    else:
        entries = glossary.get("terms") or []
        terms["entries"] = len(entries)
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            term = entry.get("term") or ""
            zh = entry.get("zh") or ""
            zh_hits = 0
            for rel, data in report["files"].items():
                if data["category"] not in ("translated", "partial"):
                    continue
                path = root / rel
                lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
                regions = classify_lines(lines)
                for n, raw, kind in regions:
                    if kind != "prose":
                        continue
                    s = raw.strip()
                    if any(rx.search(s) for rx in allow):
                        continue
                    if zh and zh in s:
                        zh_hits += 1
                    for bad in entry.get("forbidden") or []:
                        if bad and bad in s:
                            terms["violations"].append(
                                {
                                    "file": rel,
                                    "line": n,
                                    "term": term,
                                    "expected": zh,
                                    "found": bad,
                                    "text": s[:160],
                                }
                            )
                            report["errors"].append(
                                "术语表违规：%s:%d 用了禁用译法「%s」，应为「%s」" % (rel, n, bad, zh)
                            )
            if zh and zh_hits == 0:
                terms["missing_zh"].append({"term": term, "zh": zh})
        terms["violations"].sort(key=lambda x: (x["file"], x["line"]))
        if terms["missing_zh"]:
            report["warnings"].append("术语表条目在语料中未出现：%s" % ", ".join(x["zh"] for x in terms["missing_zh"]))
    report["checks"]["glossary"] = terms

    # ---------------- 结构回归 / 与英文原文比对 ----------------
    struct = {"source_dir": args.source_dir, "baseline": args.baseline, "diffs": [], "baseline_diffs": []}
    if args.source_dir:
        sd = Path(args.source_dir)
        for rel, data in report["files"].items():
            src = sd / rel
            if not src.exists():
                continue
            slines = src.read_text(encoding="utf-8", errors="replace").splitlines()
            sstruct = structure_of(slines, classify_lines(slines))
            for d in compare_structures(sstruct, data["structure"], rel):
                struct["diffs"].append(d)
                if d["severity"] == "error":
                    report["errors"].append("结构丢失：%s %s" % (rel, d["message"]))
                else:
                    report["warnings"].append("结构变化：%s %s" % (rel, d["message"]))
    if args.baseline:
        bp = Path(args.baseline)
        if bp.exists():
            base = json.loads(bp.read_text(encoding="utf-8"))
            for rel, old in (base.get("files") or {}).items():
                cur = report["files"].get(rel)
                if not cur:
                    report["errors"].append("基线文件消失：%s（被删除或改名）" % rel)
                    continue
                rank = {"untranslated": 0, "index": 1, "partial": 2, "translated": 3, "generated": 3, "meta": 3}
                if rank.get(cur["category"], 0) < rank.get(old["category"], 0):
                    msg = "分类回退：%s -> %s" % (old["category"], cur["category"])
                    struct["baseline_diffs"].append({"path": rel, "message": msg, "severity": "error"})
                    report["errors"].append("回归：%s %s" % (rel, msg))
                for d in compare_structures(old.get("structure") or {}, cur["structure"], rel):
                    struct["baseline_diffs"].append(d)
                    if d["severity"] == "error":
                        report["errors"].append("结构回归：%s %s" % (rel, d["message"]))
        else:
            report["warnings"].append("基线文件 %s 不存在，跳过回归比对" % args.baseline)
    report["checks"]["structure"] = struct

    report["summary"] = {
        "errors": len(report["errors"]),
        "warnings": len(report["warnings"]),
        "ok": not report["errors"],
    }
    return report


def compare_structures(base, cur, rel):
    diffs = []

    def err(msg):
        diffs.append({"path": rel, "message": msg, "severity": "error"})

    def warn(msg):
        diffs.append({"path": rel, "message": msg, "severity": "warning"})

    if cur["fence_count"] < base.get("fence_count", 0):
        err("围栏代码块 %d -> %d" % (base.get("fence_count", 0), cur["fence_count"]))
    if base.get("fence_langs") and cur["fence_langs"] != base["fence_langs"]:
        err("代码块语言序列变化 %s -> %s" % (base["fence_langs"], cur["fence_langs"]))
    bsha = base.get("fence_code_sha") or []
    csha = cur.get("fence_code_sha") or []
    for i in range(min(len(bsha), len(csha))):
        if bsha[i] != csha[i]:
            err("第 %d 个代码块的代码内容被改动（只允许翻译注释）" % (i + 1))
    if cur["mermaid_count"] < base.get("mermaid_count", 0):
        err("Mermaid 块 %d -> %d" % (base.get("mermaid_count", 0), cur["mermaid_count"]))
    elif base.get("mermaid_sha") and cur.get("mermaid_sha") != base["mermaid_sha"]:
        err("Mermaid 图内容被改动")
    lost_links = sorted(set(base.get("links") or []) - set(cur["links"]))
    if lost_links:
        err("链接目标丢失：%s" % ", ".join(lost_links[:6]))
    lost_images = sorted(set(base.get("images") or []) - set(cur["images"]))
    if lost_images:
        err("图片丢失：%s" % ", ".join(lost_images[:6]))
    lost_components = sorted(set(base.get("components") or []) - set(cur["components"]))
    if lost_components:
        err("MDX 组件丢失：%s" % ", ".join(lost_components[:6]))
    if cur["heading_count"] < base.get("heading_count", 0):
        err("标题数量 %d -> %d" % (base.get("heading_count", 0), cur["heading_count"]))
    base_levels = [x["level"] for x in (base.get("headings") or [])]
    cur_levels = [x["level"] for x in (cur.get("headings") or [])]
    if base_levels and base_levels != cur_levels:
        err("标题层级序列变化 %s -> %s" % (base_levels, cur_levels))
    if cur["table_count"] < base.get("table_count", 0):
        err("表格数量 %d -> %d" % (base.get("table_count", 0), cur["table_count"]))
    lost_anchors = sorted(set(base.get("anchors") or []) - set(cur["anchors"]))
    if lost_anchors:
        err("锚点丢失：%s" % ", ".join(lost_anchors[:6]))
    for name, count in (base.get("inline_code") or {}).items():
        if cur["inline_code"].get(name, 0) < count:
            warn("行内代码数量下降：%s %d -> %d" % (name, count, cur["inline_code"].get(name, 0)))
    return diffs


# --------------------------------------------------------------------------
# 输出
# --------------------------------------------------------------------------


def print_report(report, max_list):
    c = report["checks"]
    cov = c["coverage"]
    out = []
    out.append("TypeSafe 文档中文化审计")
    out.append("=" * 60)
    out.append("纳入统计的 Markdown 文件：%d（另有自动生成 %d 个、仓库文档 %d 个，不计入）" % (
        cov["files_in_scope"], cov["files_by_category"].get("generated", 0),
        cov["files_by_category"].get("meta", 0)))
    out.append("分类：已翻译 %d / 部分翻译 %d / 未翻译 %d / 索引页 %d" % (
        cov["files_by_category"].get("translated", 0),
        cov["files_by_category"].get("partial", 0),
        cov["files_by_category"].get("untranslated", 0),
        cov["files_by_category"].get("index", 0),
    ))
    out.append("文件覆盖率（已翻译/纳入范围）：%.1f%%" % (cov["file_coverage"] * 100))
    out.append("词数覆盖率（已翻译+部分/总计）：%.1f%%  (%d / %d 词)" % (
        cov["word_coverage"] * 100, cov["prose_words_by_category"].get("translated", 0)
        + cov["prose_words_by_category"].get("partial", 0), cov["prose_words_total"]))

    out.append("")
    out.append("-- 未翻译文件（按正文字数降序，最多 %d 条）%s" % (max_list, "-" * 10))
    untr = sorted([(v["prose_words"], k) for k, v in report["files"].items() if v["category"] == "untranslated"], reverse=True)
    for w, k in untr[:max_list]:
        out.append("   %6d 词  %s" % (w, k))
    if len(untr) > max_list:
        out.append("   ... 其余 %d 个见 JSON 报告" % (len(untr) - max_list))

    part = sorted([(v["prose_words"], k, v["cjk_ratio"]) for k, v in report["files"].items() if v["category"] == "partial"], reverse=True)
    if part:
        out.append("")
        out.append("-- 部分翻译文件 %s" % ("-" * 38))
        for w, k, r in part[:max_list]:
            out.append("   %6d 词  CJK %.0f%%  %s" % (w, r * 100, k))

    mx = c["mixed_language"]
    out.append("")
    out.append("-- 混排残留（中文文件里的英文段落）：%d 处，涉及 %d 个文件 %s" % (
        mx["count"], len(mx["files"]), "-" * 6))
    for m in mx["findings"][:max_list]:
        out.append("   %s:%d  [%s] %s" % (m["path"], m["start_line"], m["kind"], m["text"][:110]))
    if mx["count"] > max_list:
        out.append("   ... 其余 %d 处见 JSON 报告" % (mx["count"] - max_list))

    nav = c["navigation"]
    out.append("")
    out.append("-- 导航覆盖 %s" % ("-" * 46))
    out.append("   docs.json 引用页面：%d 个；死链：%d 个" % (nav["pages"], len(nav["missing"])))
    for m in nav["missing"]:
        out.append("   死链 %s" % m)
    out.append("   导航条目未翻译：%d 个（另有自动生成的 SDK 参考页 %d 个，不在人工翻译范围）" % (
        len(nav["untranslated"]), len(nav["generated"])))
    for u in nav["untranslated"][:max_list]:
        if not u["file"].startswith("sdk/"):
            out.append("   [%s] %s" % (u["category"], u["page"]))
    if nav["labels_untranslated"]:
        out.append("   导航标签仍是英文：%s" % ", ".join(nav["labels_untranslated"]))

    g = c["glossary"]
    out.append("")
    out.append("-- 术语表合规（来源：%s）%s" % (report["glossary_source"], "-" * 20))
    out.append("   词条 %d 个；禁用译法违规 %d 处；未在语料中出现的词条 %d 个" % (
        g["entries"], len(g["violations"]), len(g["missing_zh"])))
    for v in g["violations"][:max_list]:
        out.append("   %s:%d  用了「%s」，应为「%s」" % (v["file"], v["line"], v["found"], v["expected"]))

    st = c["structure"]
    out.append("")
    out.append("-- 结构保真 %s" % ("-" * 46))
    if st["source_dir"]:
        out.append("   与英文原文目录 %s 比对：%d 处差异" % (st["source_dir"], len(st["diffs"])))
    else:
        out.append("   未提供 --source-dir，跳过与英文原文的逐项比对")
    out.append("   与基线 %s 比对：%d 处差异" % (st["baseline"] or "(未提供)", len(st["baseline_diffs"])))
    for d in st["baseline_diffs"][:max_list]:
        out.append("   [%s] %s %s" % (d["severity"], d["path"], d["message"]))
    for d in st["diffs"][:max_list]:
        out.append("   [%s] %s %s" % (d["severity"], d["path"], d["message"]))

    out.append("")
    out.append("=" * 60)
    out.append("结论：%s  (error %d / warning %d)" % (
        "PASS" if report["summary"]["ok"] else "FAIL", report["summary"]["errors"], report["summary"]["warnings"]))
    for e in report["errors"][:max_list]:
        out.append("  ERROR   %s" % e)
    if len(report["errors"]) > max_list:
        out.append("  ... 其余 %d 条 error 见 JSON 报告" % (len(report["errors"]) - max_list))
    print("\n".join(out))


def main(argv=None):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="TypeSafe 文档中文化审计器")
    ap.add_argument("--root", default=str(here.parent), help="仓库根目录")
    ap.add_argument("--docs", default="docs.json", help="Mintlify 导航配置（相对根目录）")
    ap.add_argument("--glossary", default="tools/glossary.yml", help="术语表路径（相对根目录）")
    ap.add_argument("--source-dir", default=None, help="英文原文目录，用于结构逐项比对")
    ap.add_argument("--baseline", default=None, help="结构基线 JSON，用于检测结构回归")
    ap.add_argument("--write-baseline", default=None, help="把当前结构指纹写入基线 JSON")
    ap.add_argument("--json", dest="json_out", default=None, help="JSON 报告输出路径，- 表示 stdout")
    ap.add_argument("--untranslated-below", type=float, default=0.05, help="CJK 占比低于此值判为未翻译")
    ap.add_argument("--translated-above", type=float, default=0.45, help="CJK 占比高于此值判为已翻译")
    ap.add_argument("--mixed-min-words", type=int, default=6, help="混排检测：正文行判定为英文的最少词数")
    ap.add_argument("--heading-min-words", type=int, default=1, help="混排检测：标题行判定为英文的最少词数")
    ap.add_argument("--min-prose-words", type=int, default=20, help="正文字数低于此值归为索引页")
    ap.add_argument("--max-list", type=int, default=25, help="人类可读摘要中每节最多列出的条目数")
    ap.add_argument("--strict", action="store_true", help="存在 error 时以退出码 1 失败")
    args = ap.parse_args(argv)

    report = audit(args)

    if args.write_baseline:
        snap_files = {}
        for k, v in report["files"].items():
            if v["category"] == "generated":
                # 自动生成内容（sdk/**）由上游重新生成，不纳入结构回归保护。
                continue
            st = dict(v["structure"])
            st["headings"] = [{"level": x["level"]} for x in st.get("headings") or []]
            snap_files[k] = {"category": v["category"], "prose_words": v["prose_words"], "structure": st}
        snap = {
            "schema": report["schema"],
            "note": "结构基线：由 tools/i18n_audit.py --write-baseline 生成，用于检测后续提交的结构回归（围栏代码块内容、链接、图片、MDX 组件、标题层级、锚点、表格）。上游内容真实变化时可重新生成。",
            "files": snap_files,
        }
        Path(args.write_baseline).write_text(
            json.dumps(snap, ensure_ascii=False, indent=1, sort_keys=True) + "\n", encoding="utf-8")
        print("已写入基线：%s（%d 个文件）" % (args.write_baseline, len(snap["files"])))

    if args.json_out:
        payload = json.dumps(report, ensure_ascii=False, indent=1)
        if args.json_out == "-":
            print(payload)
        else:
            Path(args.json_out).write_text(payload + "\n", encoding="utf-8")

    if args.json_out != "-":
        print_report(report, args.max_list)

    if args.strict and report["errors"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
